### ISSUE TITLE
I just wanted to say thanks

### ISSUE THREAD

**Issue by Tahinli** [farfaaa/asus_zenbook_UM3402YA#1]
Thanks a lot my friend. I have been working to solve this sound problem for a while. You saved me.

I also forked your repo and translated in my main language, so it can reach another people who don't know English.
https://github.com/Tahinli/Asus-Zenbook-UM3402YA-Ses-Sorunu

Thanks a lot again.

**Comment by farfaaa** [comment]
Hello @Tahinli !

I saw that you added the repo link in the arch linux wiki, thanks !
However there is a mistake in the link, can you correct it ? (I don't have an account on this site)

**Comment by Tahinli** [comment]
> Hello @Tahinli !
> 
> I saw that you added the repo link in the arch linux wiki, thanks ! However there is a mistake in the link, can you correct it ? (I don't have an account on this site)

oh sorry for mistake, i can correct if you guide me
edit1: I think there is a link problem or something. It was working when i wrote this but now it seems there is a problem
edit2: as much as i can see, you changed the name of the repo. I'm going to correct it to new one.
edit3: btw i also added posibility of harming your device note when i wrote before, should i keep it or leave it
edit4: i corrected, you can check now. if you see any other mistake, I will be here for correction. it's the least i can do

**Comment by Tahinli** [comment]
I think there is a link problem or something. It was working when i wrote this but now it seems there is a problem

**Comment by farfaaa** [comment]
>edit2: as much as i can see, you changed the name of the repo. I'm going to correct it to new one.

The repo name never changed :)

>edit4: i corrected, you can check now. if you see any other mistake, I will be here for correction. it's the least i can do

It works !

**Comment by leodahal4** [comment]
I donot have experience for using these sort of tools and I am getting the below error while trying to compile the dsl file can you help me here?


```
iasl -tc ssdt_csc3551.dsl 

Intel ACPI Component Architecture
ASL+ Optimizing Compiler/Disassembler version 20230628
Copyright (c) 2000 - 2023 Intel Corporation

Error    6126 -  Compiler aborting due to parser-detected syntax error(s)


ssdt_csc3551.dsl      1: 
Error    6126 - syntax error and premature End-Of-File

Error    6126 -  Compiler aborting due to parser-detected syntax error(s)


ssdt_csc3551.dsl      1: 
Error    6126 - syntax error and premature End-Of-File

Input file:    ssdt_csc3551.dsl - Compilation aborted due to parser-detected syntax error(s)
Hex Dump:      ssdt_csc3551.hex -     238 bytes

Compilation failed. 2 Errors, 0 Warnings, 0 Remarks
No AML files were generated due to syntax error(s)

```

**Comment by Tahinli** [comment]
> I donot have experience for using these sort of tools and I am getting the below error while trying to compile the dsl file can you help me here?
> 
> ```
> iasl -tc ssdt_csc3551.dsl 
> 
> Intel ACPI Component Architecture
> ASL+ Optimizing Compiler/Disassembler version 20230628
> Copyright (c) 2000 - 2023 Intel Corporation
> 
> Error    6126 -  Compiler aborting due to parser-detected syntax error(s)
> 
> 
> ssdt_csc3551.dsl      1: 
> Error    6126 - syntax error and premature End-Of-File
> 
> Error    6126 -  Compiler aborting due to parser-detected syntax error(s)
> 
> 
> ssdt_csc3551.dsl      1: 
> Error    6126 - syntax error and premature End-Of-File
> 
> Input file:    ssdt_csc3551.dsl - Compilation aborted due to parser-detected syntax error(s)
> Hex Dump:      ssdt_csc3551.hex -     238 bytes
> 
> Compilation failed. 2 Errors, 0 Warnings, 0 Remarks
> No AML files were generated due to syntax error(s)
> ```

I don't know how to solve, but if you want i can share compiled one (I compiled in my computer).

**Comment by farfaaa** [comment]
@leodahal4,
How to get the dsl file ?
Can you try to download the  dsl file with curl or wget :

`wget https://raw.githubusercontent.com/farfaaa/asus_zenbook_UM3402YA/main/ssdt_csc3551.dsl`
or
`curl -O https://raw.githubusercontent.com/farfaaa/asus_zenbook_UM3402YA/main/ssdt_csc3551.dsl`
then
`iasl -tc ssdt_csc3551.dsl `

I just tested  on Ubuntu 22.04 without problems

**Comment by Mangoostoos** [comment]
My first acquaintance with Linux and first big trouble with this sound bug on new laptop.

Your guide is the last hope for me, but I just have no understanding what to do with ssdt_csc3551.dsl file. 
Should I edit it or not? Which corrections needed?

**Comment by farfaaa** [comment]
> Should I edit it or not? Which corrections needed?

The dsl file can be used as is, you just need to download and compile it with `iasl` (package acpica-tools on ubuntu).
You can edit it before compiling it, if you have personal optimizations to add.

**Comment by Mangoostoos** [comment]
> > Should I edit it or not? Which corrections needed?
> 
> The dsl file can be used as is, you just need to download and compile it with `iasl` (package acpica-tools on ubuntu). You can edit it before compiling it, if you have personal optimizations to add.

Bingo! It works as it is, just like u sad. Thank's friend!
