### ISSUE TITLE
What do you mean by irrelevant ?

### ISSUE THREAD

**Issue by Tahinli** [farfaaa/asus_zenbook_UM3402YA#12]
Hi, "Note: This is irrelevant for kernel >= 6.8" what do you mean by this quote ?

**Comment by farfaaa** [comment]
Hi !
It's a typo, i mean 'irrelevant', thanks for noticing that.

**Comment by Tahinli** [comment]
> Hi ! It's a typo, i mean 'irrelevant', thanks for noticing that.

No, no I'm not asking that. What happened in kernel 6.8 for our patch ? Why it's irrelevant

**Comment by farfaaa** [comment]
I mean there is no need patch, it is now included in kernel 6.8 (and superior), everything works out of the box.
If you use a kernel >= 6.8, you can delete our patch (tested and approved).

**Comment by Tahinli** [comment]
Thanks a lot it's awesome
