### ISSUE TITLE
 15 non-ASCII characters

### ISSUE THREAD

**Issue by yuriiSulak** [farfaaa/asus_zenbook_UM3402YA#9]
iasl -tc ssdt_csc3551.dsl 

Intel ACPI Component Architecture
ASL+ Optimizing Compiler/Disassembler version 20200925
Copyright (c) 2000 - 2020 Intel Corporation

File appears to be binary: found 15 non-ASCII characters, disassembling
Binary file does not contain a valid ACPI table

Compilation successful. 0 Errors, 0 Warnings, 0 Remarks, 0 Optimizations

**Comment by farfaaa** [comment]
Hello @yuriiSulak ,

How to get the dsl file ?
Can you try to download the dsl file with curl or wget :
`wget https://raw.githubusercontent.com/farfaaa/asus_zenbook_UM3402YA/main/ssdt_csc3551.dsl`
or
`curl -O https://raw.githubusercontent.com/farfaaa/asus_zenbook_UM3402YA/main/ssdt_csc3551.dsl`
then
`iasl -tc ssdt_csc3551.dsl `


you should get the following result:
```
$ iasl -tc ssdt_csc3551.dsl 

Intel ACPI Component Architecture
ASL+ Optimizing Compiler/Disassembler version 20200925
Copyright (c) 2000 - 2020 Intel Corporation

ASL Input:     ssdt_csc3551.dsl -    1711 bytes      2 keywords     39 source lines
AML Output:    ssdt_csc3551.aml -     401 bytes      0 opcodes       2 named objects
Hex Dump:      ssdt_csc3551.hex -    4245 bytes

Compilation successful. 0 Errors, 0 Warnings, 0 Remarks, 0 Optimizations

```

**Comment by yuriiSulak** [comment]
My zenbook model is UM3402Y
@farfaaa it's still the same
![image](https://github.com/farfaaa/asus_zenbook_UM3402YA/assets/58168187/60e87ad9-a1f2-4716-bd73-3fc3410a0712)

**Comment by farfaaa** [comment]
@yuriiSulak, 
In your screenshot you download a file named 'ssdt_csc3551.dsl.1' but you compile a file named 'ssdt_csc3551.dsl'.
